version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - tunnel
    expose:
      - "9000" # php-fpm

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: always
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - tunnel
    depends_on:
      - app

networks:
  tunnel:
    external: true
